#!/bin/bash

webappname=CACSTUnicorn
#resource-group is also named as CACSTUnicorn
myResourceGroup=CACSTRubyTeam
# replease with your project repository
gitrepo=https://github.com/thyngontran/tourney.git


# Create a resource group.
az group create --location eastus --name $myResourceGroup

# Create an App Service plan in STANDARD tier (minimum required by deployment slots).
az appservice plan create --name $webappname --resource-group $myResourceGroup --sku S1

# Create a web app.
az webapp create --name $webappname --resource-group $myResourceGroup --plan $webappname
# goto link below and verified webapp shell created successfully
echo http://$webappname.azurewebsites.net

#Create a deployment slot with the name "staging".
az webapp deployment slot create --name $webappname --resource-group $myResourceGroup --slot staging


# Deploy sample code to "staging" slot from GitHub.
az webapp deployment source config --name $webappname --resource-group $myResourceGroup --slot staging --repo-url $gitrepo --branch master --manual-integration


az webapp deployment source sync --name $webappname --resource-group $myResourceGroup --slot staging

# Copy the result of the following command into a browser to see the staging slot.
echo http://$webappname-staging.azurewebsites.net

# Swap the verified/warmed up staging slot into production.
az webapp deployment slot swap --name $webappname --resource-group $myResourceGroup --slot staging
echo http://$webappname.azurewebsites.net


#cleanup 
az group delete --name $myResourceGroup